// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circulation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopyCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CutMargin")
                        .HasColumnType("real");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCalculatePrice")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheckFile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCmyk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomCirculation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomPage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomSize")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCirculation")
                        .HasColumnType("int");

                    b.Property<float?>("MaxLength")
                        .HasColumnType("real");

                    b.Property<int?>("MaxPage")
                        .HasColumnType("int");

                    b.Property<float?>("MaxWidth")
                        .HasColumnType("real");

                    b.Property<int?>("MinCirculation")
                        .HasColumnType("int");

                    b.Property<float?>("MinLength")
                        .HasColumnType("real");

                    b.Property<int?>("MinPage")
                        .HasColumnType("int");

                    b.Property<float?>("MinWidth")
                        .HasColumnType("real");

                    b.Property<string>("PageCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrintMargin")
                        .HasColumnType("real");

                    b.Property<byte>("PrintSide")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<byte>("ProductType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SheetDimensionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdtId")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<byte?>("Side")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAdts");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdtPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProductAdtId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdtTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPriceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductAdtId");

                    b.ToTable("ProductAdtPrices");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdtType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdtTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductAdtId");

                    b.ToTable("ProductAdtTypes");
                });

            modelBuilder.Entity("Domain.Entities.ProductDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("CalcType")
                        .HasColumnType("tinyint");

                    b.Property<int>("EndCirculation")
                        .HasColumnType("int");

                    b.Property<bool>("IsIncreased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<byte>("PrintSide")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StartCirculation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDelivers");
                });

            modelBuilder.Entity("Domain.Entities.ProductDeliverSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductDeliverId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductDeliverId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("ProductDeliverSizes");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCombinedMaterial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomCirculation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterialAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaterialId");

                    b.ToTable("ProductMaterialAttributes");
                });

            modelBuilder.Entity("Domain.Entities.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Circulation")
                        .HasColumnType("int");

                    b.Property<int?>("CopyCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDoubleSided")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("ProductMaterialAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPrintKindId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaterialAttributeId");

                    b.HasIndex("ProductMaterialId");

                    b.HasIndex("ProductPrintKindId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("Domain.Entities.ProductPrintKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("PrintKindId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrintKinds");
                });

            modelBuilder.Entity("Domain.Entities.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetCount")
                        .HasColumnType("int");

                    b.Property<int>("SheetDimensionId")
                        .HasColumnType("int");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdt", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Adts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdtPrice", b =>
                {
                    b.HasOne("Domain.Entities.ProductAdt", "ProductAdt")
                        .WithMany("Prices")
                        .HasForeignKey("ProductAdtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAdt");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdtType", b =>
                {
                    b.HasOne("Domain.Entities.ProductAdt", "ProductAdt")
                        .WithMany("Types")
                        .HasForeignKey("ProductAdtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAdt");
                });

            modelBuilder.Entity("Domain.Entities.ProductDeliver", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Delivers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductDeliverSize", b =>
                {
                    b.HasOne("Domain.Entities.ProductDeliver", "ProductDeliver")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductDeliverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductSize", "ProductSize")
                        .WithMany("DeliverSizes")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductDeliver");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterial", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Materials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterialAttribute", b =>
                {
                    b.HasOne("Domain.Entities.ProductMaterial", "ProductMaterial")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductMaterial");
                });

            modelBuilder.Entity("Domain.Entities.ProductPrice", b =>
                {
                    b.HasOne("Domain.Entities.ProductMaterialAttribute", "ProductMaterialAttribute")
                        .WithMany()
                        .HasForeignKey("ProductMaterialAttributeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.ProductMaterial", "ProductMaterial")
                        .WithMany()
                        .HasForeignKey("ProductMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductPrintKind", "ProductPrintKind")
                        .WithMany()
                        .HasForeignKey("ProductPrintKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductSize", "ProductSize")
                        .WithMany()
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductMaterial");

                    b.Navigation("ProductMaterialAttribute");

                    b.Navigation("ProductPrintKind");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("Domain.Entities.ProductPrintKind", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("PrintKinds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductSize", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("Adts");

                    b.Navigation("Delivers");

                    b.Navigation("Materials");

                    b.Navigation("PrintKinds");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Domain.Entities.ProductAdt", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("Domain.Entities.ProductDeliver", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterial", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("Domain.Entities.ProductSize", b =>
                {
                    b.Navigation("DeliverSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
